import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface CommuneData {
  name: string;
  wilaya: string;
  wilayaCode: number;
}

const communes: CommuneData[] = [
  // 01 - Adrar
  { name: 'Adrar', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Timimoun', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Reggane', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'In Salah', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Aoulef', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Timiaouine', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Tit', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Ksar Kaddour', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Tsabit', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Slimane', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Deldoul', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Zaouiet Kounta', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Aougrout', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Tamekten', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Tamantit', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Fenoughil', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Tinerkouk', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Djanet', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Ighadir', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Talmine', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Sbaa', wilaya: 'Adrar', wilayaCode: 1 },
  { name: 'Timiaouine', wilaya: 'Adrar', wilayaCode: 1 },

  // 02 - Chlef
  { name: 'Chlef', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Ténès', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'El Karimia', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Tadjena', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Talassa', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Herenfa', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'AArbta', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Labiod Medjdoubia', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'El Asnam', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Beni Boussaid', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Marhoum', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Terga', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Sidi Abderrahmane', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Sidi Akkacha', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Beni Choukri', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Oued Fodda', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Oued Sly', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Beni Haoua', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Taourga', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Ouled Ben Abdelkader', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Ain Merane', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Breira', wilaya: 'Chlef', wilayaCode: 2 },
  { name: 'Bouzeguene', wilaya: 'Chlef', wilayaCode: 2 },

  // 03 - Laghouat
  { name: 'Laghouat', wilaya: 'Laghouat', wilayaCode: 3 },
  { name: 'Aflou', wilaya: 'Laghouat', wilayaCode: 3 },
  { name: 'Sidi Makhlouf', wilaya: 'Laghouat', wilayaCode: 3 },
  { name: 'Hassi R Mel', wilaya: 'Laghouat', wilayaCode: 3 },
  { name: 'Ksar El Boukhari', wilaya: 'Laghouat', wilayaCode: 3 },
  { name: 'Ain Sidi Ali', wilaya: 'Laghouat', wilayaCode: 3 },
  { name: 'El Hafaia', wilaya: 'Laghouat', wilayaCode: 3 },
  { name: 'Sidi Saad', wilaya: 'Laghouat', wilayaCode: 3 },
  { name: 'Ain El Hadjel', wilaya: 'Laghouat', wilayaCode: 3 },
  { name: 'Tadjmout', wilaya: 'Laghouat', wilayaCode: 3 },
  { name: 'Kheneg', wilaya: 'Laghouat', wilayaCode: 3 },
  { name: 'Gueltat Sidi Saad', wilaya: 'Laghouat', wilayaCode: 3 },
  { name: 'Ain Beni Mathar', wilaya: 'Laghouat', wilayaCode: 3 },
  { name: 'El Assafia', wilaya: 'Laghouat', wilayaCode: 3 },
  { name: 'Oued M Sayeh', wilaya: 'Laghouat', wilayaCode: 3 },
  { name: 'Sidi Rached', wilaya: 'Laghouat', wilayaCode: 3 },

  // 04 - Oum El Bouaghi
  { name: 'Oum El Bouaghi', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'Ain Beida', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'Bir Chouhada', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'Selaoui', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'Ain Fekroune', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'Ain Kercha', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'El Aouinet', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'El Harmilia', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'Hamma', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'Meskiana', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'Ain Babouche', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'Bir Boussoula', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'Ksar Sbahi', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'Oued Nini', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'Ouled Hamla', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'Ouled Zouai', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'Tiaret', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },
  { name: 'Zrig', wilaya: 'Oum El Bouaghi', wilayaCode: 4 },

  // 05 - Batna
  { name: 'Batna', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Barika', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Guelaata', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Ngaous', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Guerrah', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Tigharghar', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Ain Touta', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Djezzar', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Takmert', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'El Mansoura', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Sidi Medjez', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Timgad', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Bouzina', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Fesdis', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Ouled Selim', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Larbaa', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Tazoult', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Ouyoun El Assafir', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'El Kantara', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Ain Djasser', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Ouled Smail', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Bouhmama', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Kimmel', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Ouled Fadel', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Tiglit', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Merouana', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Seriana', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Zenina', wilaya: 'Batna', wilayaCode: 5 },
  { name: 'Bouzeguene', wilaya: 'Batna', wilayaCode: 5 },

  // 06 - Béjaïa
  { name: 'Bejaia', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Akbou', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Sidi Aich', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'El Kseur', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Toudja', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Amizour', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Ferraoun', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Tichy', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Souk El Tenine', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Mih Ouassene', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Ighil Ali', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Ouzellaguen', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Bouhamza', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Beni Maouche', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Chemini', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Ouadhias', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Ait Rizine', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Ain Romane', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Ouled Adjel', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Tala Guilef', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Barbacha', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Sidi Ayad', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Ain El Kebira', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Beni Mellikeche', wilaya: 'Bejaia', wilayaCode: 6 },
  { name: 'Sidi Bel Abbes', wilaya: 'Bejaia', wilayaCode: 6 },

  // 07 - Biskra
  { name: 'Biskra', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'Tolga', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'Sidi Okba', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'Mechira', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'Zeribet El Oued', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'El Kantara', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'Ain Naga', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'Foughara', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'Zemoura', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'Lioua', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'Timgchout', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'Ouled Djellal', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'Bordj El Haouas', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'Chetma', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'Touggourt', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'El Outaya', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'Djemorah', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'Branis', wilaya: 'Biskra', wilayaCode: 7 },
  { name: 'Sidi Khaled', wilaya: 'Biskra', wilayaCode: 7 },

  // 08 - Béchar
  { name: 'Bechar', wilaya: 'Bechar', wilayaCode: 8 },
  { name: 'El Bayadh', wilaya: 'Bechar', wilayaCode: 8 },
  { name: 'Bou Craa', wilaya: 'Bechar', wilayaCode: 8 },
  { name: 'Lahmar', wilaya: 'Bechar', wilayaCode: 8 },
  { name: 'Kenadsa', wilaya: 'Bechar', wilayaCode: 8 },
  { name: 'Beni Ounif', wilaya: 'Bechar', wilayaCode: 8 },
  { name: 'Tabelbala', wilaya: 'Bechar', wilayaCode: 8 },
  { name: 'Taghit', wilaya: 'Bechar', wilayaCode: 8 },
  { name: 'Kerzaz', wilaya: 'Bechar', wilayaCode: 8 },
  { name: 'Timoudi', wilaya: 'Bechar', wilayaCode: 8 },
  { name: 'Abadla', wilaya: 'Bechar', wilayaCode: 8 },
  { name: 'Beni Ikhlef', wilaya: 'Bechar', wilayaCode: 8 },
  { name: 'Mechraa Bel Ksiri', wilaya: 'Bechar', wilayaCode: 8 },
  { name: 'El Ouata', wilaya: 'Bechar', wilayaCode: 8 },
  { name: 'Boukais', wilaya: 'Bechar', wilayaCode: 8 },
  { name: 'Ghalaba', wilaya: 'Bechar', wilayaCode: 8 },

  // 09 - Blida
  { name: 'Blida', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'Boufarik', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'Mouzaia', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'Bougara', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'Hamam Melouane', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'Beni Mered', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'Bougara', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'Guerouaoua', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'Ain El Turck', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'Beni Tamou', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'Bouarfa', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'Chrea', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'El Affroun', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'Chiffa', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'Hennaya', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'Ouled Yaich', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'Grimid', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'El Komria', wilaya: 'Blida', wilayaCode: 9 },
  { name: 'Beni Khellil', wilaya: 'Blida', wilayaCode: 9 },

  // 10 - Bouira
  { name: 'Bouira', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Sour El Ghozlane', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Ain Bessem', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Bir Ghbalou', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Dirah', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'El Hachimia', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Haizer', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Kadiria', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Lakhdaria', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Mchedallah', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Souk El Khemis', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Ain El Hadjar', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Bouderbala', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Zbarbar', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Ain Laloui', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Hadjout Zerara', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Maala', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Ouled Rached', wilaya: 'Bouira', wilayaCode: 10 },
  { name: 'Ain Boudinar', wilaya: 'Bouira', wilayaCode: 10 },

  // 11 - Tlemcen
  { name: 'Tlemcen', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Maghnia', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Ghazaouet', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Hennaya', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Zouiat', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Maghnia', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Nedroma', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Mansourah', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Terni', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'El Gor', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Sebdou', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Beni Saf', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'El Aricha', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Remchi', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Fellaoucene', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Ain Taref', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Hama', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Nedroma', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Sidi Djaballah', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Tianet', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Souani', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Dar Yaghmouracene', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Ain Fezza', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Ouled Mimoun', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Amieur', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Ain Youcef', wilaya: 'Tlemcen', wilayaCode: 11 },
  { name: 'Zenata', wilaya: 'Tlemcen', wilayaCode: 11 },

  // 12 - Tizi Ouzou
  { name: 'Tizi Ouzou', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Azazga', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Draa Ben Khedda', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Ouadhias', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Azazga', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Maatka', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Ain El Hammam', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Akbil', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Bouzeguene', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Ain Yaiche', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Timizart', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Ain Kihal', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Tigzirt', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Ait Yahia', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Ait Bouadif', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Ait Toudert', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Mekla', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Ait Chaffaa', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Tirmitine', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Ait Youssef Ali', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Tadmaït', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Ouacif', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Ider', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Ain Zaatout', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Beni Douala', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Illilten', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Bouzguen', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Ait Aggouacha', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Iferhounene', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Ait Aissa Mimoun', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Assi Youcef', wilaya: 'Tizi Ouzou', wilayaCode: 12 },
  { name: 'Ain Zaatout', wilaya: 'Tizi Ouzou', wilayaCode: 12 },

  // 13 - Algiers
  { name: 'Alger Centre', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Sidi M\'Hamed', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'El Biar', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Bouzareah', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'El Madania', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'El Hamiz', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Bir Mourad Rais', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Bir Touta', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Hussein Dey', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Kouba', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'El Harrach', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Baraki', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Birtouta', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Zeralda', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Draria', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Dely Ibrahim', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Bab Ezzouar', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Bab El Oued', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Boucherouite', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Oued Koriche', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Bainem', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Herraoua', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Reghaia', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Rouiba', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Reghaia', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'El Magharia', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Benni Messous', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'El Bouzareah', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Ain Benian', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Staoueli', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Zeralda', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Mahelma', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Rahmania', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Souidania', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Cheraga', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Ouled Fayet', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'El Achour', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Draria', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Dely Ibrahim', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Kniss', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Mohammadia', wilaya: 'Alger', wilayaCode: 13 },
  { name: 'Bouzareah', wilaya: 'Alger', wilayaCode: 13 },

  // 14 - Djelfa
  { name: 'Djelfa', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Ain Oussera', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Bouira Lahdab', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Charef', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'El Khaled', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Messaad', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Mili', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Ain El Bell', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Beni Sbah', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Dar Es Salam', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Douis', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'El Ikhf', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Faidh El Botma', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Hassi Bahbah', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Hassi El Euch', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Muadine', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Ouled Blal', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Sedrata', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Selmana', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Tadmit', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Zaafrane', wilaya: 'Djelfa', wilayaCode: 14 },
  { name: 'Zaccar', wilaya: 'Djelfa', wilayaCode: 14 },

  // 15 - Jijel
  { name: 'Jijel', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'El Aria', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'El Ancer', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Sidi Abdelaziz', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Kaous', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Ghebala', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Settara', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'El Kseur', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Sheikh Tano', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Dely Said', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Boussif Ouled Asker', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Moudjara', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Selma Beni', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Chaaba', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Bou Harriz El Maamoura', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Ain Kharouba', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Ouled Rais', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Texenna', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Emir Abdelkader', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Zighoud Youcef', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Chekfa', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Chahna', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Bouraoui Belkacem', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Tassadane Haddad', wilaya: 'Jijel', wilayaCode: 15 },
  { name: 'Ouled Yahia Khadash', wilaya: 'Jijel', wilayaCode: 15 },

  // 16 - Sétif
  { name: 'Setif', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Ain Oulmene', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'El Eulma', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Djemila', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Bougaa', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Maaouia', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Ain Arnat', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Amoucha', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Ain Abessa', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Dechmaa', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Bouandas', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Bousselam', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'El Ouricia', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Tizi N Bechar', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Sarzeau', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Ain Sebaa', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'El Ouldja', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Tellar', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Bir El Arch', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Beni Chebana', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'El Eulma', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Guidjel', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Ain Lahdjar', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'El Beidha', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Beni Ourtilane', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Salah Bouchaour', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Ain Mellouk', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Hamma', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Maacem', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Ouled Tebben', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Ain El Kebira', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Beni Foudala El Hakania', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Ouled Addouane', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Belaa', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Ain Roua', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Ain Sebt', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Beni Aziz', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Ouled Sabor', wilaya: 'Setif', wilayaCode: 16 },
  { name: 'Ain Berrit', wilaya: 'Setif', wilayaCode: 16 },

  // 17 - Saida
  { name: 'Saida', wilaya: 'Saida', wilayaCode: 17 },
  { name: 'Ain El Hadjar', wilaya: 'Saida', wilayaCode: 17 },
  { name: 'Ouled Brahim', wilaya: 'Saida', wilayaCode: 17 },
  { name: 'El Hadjab', wilaya: 'Saida', wilayaCode: 17 },
  { name: 'Ain Soltane', wilaya: 'Saida', wilayaCode: 17 },
  { name: 'Sidi Boumedienne', wilaya: 'Saida', wilayaCode: 17 },
  { name: 'Ain Sekhouna', wilaya: 'Saida', wilayaCode: 17 },
  { name: 'Ouled Khaled', wilaya: 'Saida', wilayaCode: 17 },
  { name: 'Moulay Larbi', wilaya: 'Saida', wilayaCode: 17 },
  { name: 'Sidi Ahmed', wilaya: 'Saida', wilayaCode: 17 },
  { name: 'Tircine', wilaya: 'Saida', wilayaCode: 17 },
  { name: 'Ain Sidi Ali', wilaya: 'Saida', wilayaCode: 17 },
  { name: 'Beni Bouated', wilaya: 'Saida', wilayaCode: 17 },
  { name: 'Hamma', wilaya: 'Saida', wilayaCode: 17 },
  { name: 'Sidi Amar', wilaya: 'Saida', wilayaCode: 17 },
  { name: 'Ain Berrit', wilaya: 'Saida', wilayaCode: 17 },

  // 18 - Skikda
  { name: 'Skikda', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'El Hadaik', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Ain Zouit', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'El Collo', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Tamalous', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Ain Kechra', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Ouldja Boulbalout', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Kheneg Mayoun', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Guelata Boudrechar', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Zitouna', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Ain Bouzegza', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Ramdane Djamel', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Beneath Youcef', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'El Boudjabeaa', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Beni Zid', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Ouled Attia', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Sidi Mezghich', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Salah Bouchaour', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Kerkera', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Zerdeza', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Emjez Edchich', wilaya: 'Skikda', wilayaCode: 18 },
  { name: 'Filfila', wilaya: 'Skikda', wilayaCode: 18 },

  // 19 - Sidi Bel Abbes
  { name: 'Sidi Bel Abbes', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Tessala', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Makedra', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Tenira', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Oued Sefioun', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Hennaya', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Moulay Slissen', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'El Amria', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Lamtar', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Sidi Ali Benyoub', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Tafissour', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Ain Tallouta', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Ras El Ma', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Ben Badis', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Sidi Shaib', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Telagh', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Toudart', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Ain Kada', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Mcid', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Sidi Hamadouche', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Belarbi', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Ouled Sidi Bellahsen', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Ain El Berd', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Sfissef', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'Ain Tetrine', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'El Ghedir', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },
  { name: 'El Biod', wilaya: 'Sidi Bel Abbes', wilayaCode: 19 },

  // 20 - Annaba
  { name: 'Annaba', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'El Bouni', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'El Hadjar', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'Eulma', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'Berrahal', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'El Eulma', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'Tocqueville', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'Oued El Aneb', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'El Boudjemaâ', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'Ain El Berd', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'Seraidi', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'Ain Balouta', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'Oued Berkeche', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'Rammel Soumareur', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'Bouati Salah', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'El Bouni', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'El Khroub', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'Ain Smara', wilaya: 'Annaba', wilayaCode: 20 },
  { name: 'Camp César', wilaya: 'Annaba', wilayaCode: 20 },

  // 21 - Guelma
  { name: 'Guelma', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Bouatiwlen', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Hammam N\'Bail', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Ain Mebarka', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Bou Hamdane', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Ain Makhlouf', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Khezara', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Beni Mezline', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Bou Guerra', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Hammam Debagh', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Medjez Sfa', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Ain Hassaene', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Senda', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Oued Zenati', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Tamlouka', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Oued Cheham', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Ain Larbi', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Bouatiwlen', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'El Fedjoudj', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Bou Hamama', wilaya: 'Guelma', wilayaCode: 21 },
  { name: 'Beni Aziz', wilaya: 'Guelma', wilayaCode: 21 },

  // 22 - Constantine
  { name: 'Constantine', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'El Khroub', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'Ain Smara', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'Ben Badis', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'El Haria', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'Zighoud Youcef', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'Didouche Mourad', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'Hamma Bouziane', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'Ibn Ziad', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'Messali Hadj', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'Beni Hamidane', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'Ouled Hellal', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'Ain Tine', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'Ain Smara', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'El Khroub', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'Niaga', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'Ouled Rahmoune', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'Belaakel', wilaya: 'Constantine', wilayaCode: 22 },
  { name: 'Ali Mendjeli', wilaya: 'Constantine', wilayaCode: 22 },

  // 23 - Médéa
  { name: 'Medea', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Ksar El Boukhari', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Ain Boucif', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Ouled Antar', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Beni Slimane', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Rebaia', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Bouaiche', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Ain Ouksir', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Tablat', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Hammauria', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Ouzera', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Ain El Hammam', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Bouqraou', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Sidi Naamane', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Ouled Bouachra', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Saneg', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Msfaf', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Tletat Ben Ali', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'El Guelbeloue', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Derrag', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Oum El Djellil', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Baata', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Beni Boudouane', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Ain El Anasser', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Chelalet El Adhaoura', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'El Hauteur', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Tafraout', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Benchicao', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Sidi Rabia', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Ain Bahloul', wilaya: 'Medea', wilayaCode: 23 },
  { name: 'Aziz', wilaya: 'Medea', wilayaCode: 23 },

  // 24 - Mostaganem
  { name: 'Mostaganem', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Hassi Mameche', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Bouguirat', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Sour', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Stilia', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Ain Nouissy', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Hadjadj', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Ouled Maallah', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Mesra', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Sidi Ali', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Mansouri', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'El Matmar', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Sidi Lakhdar', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Achaacha', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Kheiredine', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Sidi Slimane', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Ain Toudjar', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Sour El Ghozlane', wilaya: 'Mostaganem', wilayaCode: 24 },
  { name: 'Oued El Kheir', wilaya: 'Mostaganem', wilayaCode: 24 },

  // 25 - M\'Sila
  { name: 'Msila', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Bou Saada', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Ain El Hadjel', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Sidi Aissa', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Ain Sidi Ali', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Beni Ilmane', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Bouzegama', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Chellal', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'El Hamel', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Ouled Derradj', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Sidi Ameur', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Tarmount', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Mhtarla', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Ouled Madhi', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Hammam Dalaa', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Ouanougha', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Khadra', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Sidi Mhamed Ben Ali', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Medjedel', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Ain Errich', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Beni Aziz', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Ouled Sidi Ahmed', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Maadid', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Ain Khadra', wilaya: 'Msila', wilayaCode: 25 },
  { name: 'Ouled Attia', wilaya: 'Msila', wilayaCode: 25 },

  // 26 - Mascara
  { name: 'Mascara', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Hachem', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Ferrara', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Maoussa', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Tizi', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'El Guerdania', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Khalouia', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Oued Taria', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Ain Ferah', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Sfisef', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Ghriss', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Ain Fekane', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Tegrimat', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Aoued Sidi Abdelkader', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'El Mamounia', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Oued El Abtal', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Sidi Abdelmoumene', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Metrag', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Ain Sari', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Hacine', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Beni Chougra', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Bou Hanifia', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'El Bordj', wilaya: 'Mascara', wilayaCode: 26 },
  { name: 'Ain Fares', wilaya: 'Mascara', wilayaCode: 26 },

  // 27 - Ouargla
  { name: 'Ouargla', wilaya: 'Ouargla', wilayaCode: 27 },
  { name: 'Hassi Messaoud', wilaya: 'Ouargla', wilayaCode: 27 },
  { name: 'Rouissat', wilaya: 'Ouargla', wilayaCode: 27 },
  { name: 'Ain Beida', wilaya: 'Ouargla', wilayaCode: 27 },
  { name: 'Beni Abbes', wilaya: 'Ouargla', wilayaCode: 27 },
  { name: 'El Borma', wilaya: 'Ouargla', wilayaCode: 27 },
  { name: 'Sidi Khouiled', wilaya: 'Ouargla', wilayaCode: 27 },
  { name: 'Hassi Ben Abdellah', wilaya: 'Ouargla', wilayaCode: 27 },
  { name: 'El Guerara', wilaya: 'Ouargla', wilayaCode: 27 },
  { name: 'M\'Rara', wilaya: 'Ouargla', wilayaCode: 27 },
  { name: 'Sidi Slouhi', wilaya: 'Ouargla', wilayaCode: 27 },
  { name: 'El Allia', wilaya: 'Ouargla', wilayaCode: 27 },
  { name: 'El Biod', wilaya: 'Ouargla', wilayaCode: 27 },

  // 28 - Oran
  { name: 'Oran', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Ain Turk', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Es Senia', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Bir El Djir', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Arzew', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Ain El Turck', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Zeralda', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Marsa Ben M\'Hidi', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Oued Tlelat', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Tafraoui', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Sidi El Abbes', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Ain Kerma', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Ain El Franis', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Beni Saf', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'El Amria', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Hassi Ameur', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Misserghin', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Boufatis', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Mekhada', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Ain Biya', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Sidi Chami', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'El Orjane', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Bouhadjar', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Benzerka', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Remchi', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Ain El Yafir', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Gdyel', wilaya: 'Oran', wilayaCode: 28 },
  { name: 'Bir El Djir', wilaya: 'Oran', wilayaCode: 28 },

  // 29 - El Bayadh
  { name: 'El Bayadh', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'Rouissat', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'Bouzeguene', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'El Abiodh Sidi Cheikh', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'Ain Sefra', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'Krimim', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'El Bnoud', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'Cheguig', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'El Kheiter', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'Kasdir', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'Boualem', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'El Biod', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'Stitten', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'Moghrar', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'Mechraa Safa', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'Toushamla', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'Bougtoub', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'El Kala', wilaya: 'El Bayadh', wilayaCode: 29 },
  { name: 'Sidi Slimane', wilaya: 'El Bayadh', wilayaCode: 29 },

  // 30 - Illizi
  { name: 'Illizi', wilaya: 'Illizi', wilayaCode: 30 },
  { name: 'Bordj El Haouas', wilaya: 'Illizi', wilayaCode: 30 },
  { name: 'Djanet', wilaya: 'Illizi', wilayaCode: 30 },
  { name: 'Bemian', wilaya: 'Illizi', wilayaCode: 30 },
  { name: 'El Kala', wilaya: 'Illizi', wilayaCode: 30 },
  { name: 'Touggourt', wilaya: 'Illizi', wilayaCode: 30 },
  { name: 'El Biodh', wilaya: 'Illizi', wilayaCode: 30 },
  { name: 'Hassi Messaoud', wilaya: 'Illizi', wilayaCode: 30 },

  // 31 - Bordj Bou Arreridj
  { name: 'Bordj Bou Arreridj', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'Ras El Oued', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'Bordj Zemoura', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'El Hamadia', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'Bou Mzab', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'Ain Taghrout', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'Sidi Emmbarek', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'El Maa El Biodh', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'Tefreg', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'El Main', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'Ouled Sidi Brahim', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'Tixter', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'Belimour', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'Bir Kasdali', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'Guebelou', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'Ksour El Kheir', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'Ouled Ali', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },
  { name: 'Medjana', wilaya: 'Bordj Bou Arreridj', wilayaCode: 31 },

  // 32 - Boumerdès
  { name: 'Boumerdes', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Thénia', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Boudouaou', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Bouzegza Kchedara', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Isser', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Zemmouri', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Sebaine', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Talgua', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'El Kharrouba', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Bouali', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Ain Benian', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Lardjem', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Mansoura', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Tidjelabine', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Chabet El Ameur', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Ouled Moussa', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Si Mustapha', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Ain Taya', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Bouzeguene', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'El Boudali', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Hammedi', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Khemis El Khechna', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Belala', wilaya: 'Boumerdes', wilayaCode: 32 },
  { name: 'Harraoua', wilaya: 'Boumerdes', wilayaCode: 32 },

  // 33 - El Tarf
  { name: 'El Tarf', wilaya: 'El Tarf', wilayaCode: 33 },
  { name: 'Bouhadjar', wilaya: 'El Tarf', wilayaCode: 33 },
  { name: 'Ben M\'Hidi', wilaya: 'El Tarf', wilayaCode: 33 },
  { name: 'El Kala', wilaya: 'El Tarf', wilayaCode: 33 },
  { name: 'Ain Berda', wilaya: 'El Tarf', wilayaCode: 33 },
  { name: 'Asfour', wilaya: 'El Tarf', wilayaCode: 33 },
  { name: 'Echatt', wilaya: 'El Tarf', wilayaCode: 33 },
  { name: 'El Aiounia', wilaya: 'El Tarf', wilayaCode: 33 },
  { name: 'Bouchebka', wilaya: 'El Tarf', wilayaCode: 33 },
  { name: 'Besbes', wilaya: 'El Tarf', wilayaCode: 33 },
  { name: 'Ain Zouit', wilaya: 'El Tarf', wilayaCode: 33 },
  { name: 'Beni Chougrane', wilaya: 'El Tarf', wilayaCode: 33 },
  { name: 'Ain El Kebira', wilaya: 'El Tarf', wilayaCode: 33 },
  { name: 'Terga', wilaya: 'El Tarf', wilayaCode: 33 },

  // 34 - Tindouf
  { name: 'Tindouf', wilaya: 'Tindouf', wilayaCode: 34 },
  { name: 'Boukais', wilaya: 'Tindouf', wilayaCode: 34 },
  { name: 'Oum Toub', wilaya: 'Tindouf', wilayaCode: 34 },
  { name: 'Ain Amara', wilaya: 'Tindouf', wilayaCode: 34 },

  // 35 - Tissemsilt
  { name: 'Tissemsilt', wilaya: 'Tissemsilt', wilayaCode: 35 },
  { name: 'Bordj Bou Naama', wilaya: 'Tissemsilt', wilayaCode: 35 },
  { name: 'Ain El Hadjar', wilaya: 'Tissemsilt', wilayaCode: 35 },
  { name: 'Lazharia', wilaya: 'Tissemsilt', wilayaCode: 35 },
  { name: 'Beni Chaib', wilaya: 'Tissemsilt', wilayaCode: 35 },
  { name: 'Lardjem', wilaya: 'Tissemsilt', wilayaCode: 35 },
  { name: 'El Imama', wilaya: 'Tissemsilt', wilayaCode: 35 },
  { name: 'Sidi Boutouchent', wilaya: 'Tissemsilt', wilayaCode: 35 },
  { name: 'Theniet El Had', wilaya: 'Tissemsilt', wilayaCode: 35 },
  { name: 'Maacem', wilaya: 'Tissemsilt', wilayaCode: 35 },
  { name: 'Ouled Bessim', wilaya: 'Tissemsilt', wilayaCode: 35 },
  { name: 'Beni Lahcene', wilaya: 'Tissemsilt', wilayaCode: 35 },
  { name: 'Sidi Abed', wilaya: 'Tissemsilt', wilayaCode: 35 },
  { name: 'Ammari', wilaya: 'Tissemsilt', wilayaCode: 35 },
  { name: 'Youssoufia', wilaya: 'Tissemsilt', wilayaCode: 35 },
  { name: 'Boussad', wilaya: 'Tissemsilt', wilayaCode: 35 },
  { name: 'El Hajjar', wilaya: 'Tissemsilt', wilayaCode: 35 },

  // 36 - El Oued
  { name: 'El Oued', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Robbah', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Oued El Alenda', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Bayadha', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Djamaa', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Mih Ouensa', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'El M\'Ghair', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Sidi Aoun', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Trifaoui', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Taleb Larbi', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Douar El Ma', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'El Ogla', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Magrane', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Beni Guebal', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Sidi Khelifa', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'El Caaid', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Hassani Abdelmoumene', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Commidia', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Degache', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Ourmes', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'Tendla', wilaya: 'El Oued', wilayaCode: 36 },
  { name: 'El Ogla', wilaya: 'El Oued', wilayaCode: 36 },

  // 37 - Khenchela
  { name: 'Khenchela', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'M\'Sara', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'Bou Hamama', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'Taoura', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'Remila', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'El Hamma', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'Ain Touila', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'Bouziane', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'El Oued', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'Nechmaya', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'Ouled Rechache', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'El Kantara', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'Ain Youssef', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'Bouhmama', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'Chela', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'El Araich', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'Djellal', wilaya: 'Khenchela', wilayaCode: 37 },
  { name: 'Babar', wilaya: 'Khenchela', wilayaCode: 37 },

  // 38 - Souk Ahras
  { name: 'Souk Ahras', wilaya: 'Souk Ahras', wilayaCode: 38 },
  { name: 'Sedrata', wilaya: 'Souk Ahras', wilayaCode: 38 },
  { name: 'Haddada', wilaya: 'Souk Ahras', wilayaCode: 38 },
  { name: 'Mdaourouche', wilaya: 'Souk Ahras', wilayaCode: 38 },
  { name: 'Ain Sidi Ali', wilaya: 'Souk Ahras', wilayaCode: 38 },
  { name: 'Ouled Moumen', wilaya: 'Souk Ahras', wilayaCode: 38 },
  { name: 'Merahna', wilaya: 'Souk Ahras', wilayaCode: 38 },
  { name: 'Ouled Driss', wilaya: 'Souk Ahras', wilayaCode: 38 },
  { name: 'Tiffessad', wilaya: 'Souk Ahras', wilayaCode: 38 },
  { name: 'El Djemaa', wilaya: 'Souk Ahras', wilayaCode: 38 },
  { name: 'Ain Zouia', wilaya: 'Souk Ahras', wilayaCode: 38 },
  { name: 'Ain Senna', wilaya: 'Souk Ahras', wilayaCode: 38 },
  { name: 'Bir Bouhouche', wilaya: 'Souk Ahras', wilayaCode: 38 },
  { name: 'Oued Kebrit', wilaya: 'Souk Ahras', wilayaCode: 38 },
  { name: 'Taourit', wilaya: 'Souk Ahras', wilayaCode: 38 },
  { name: 'El Hamma', wilaya: 'Souk Ahras', wilayaCode: 38 },
  { name: 'Zouabi', wilaya: 'Souk Ahras', wilayaCode: 38 },

  // 39 - Tipaza
  { name: 'Tipaza', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'Menerville', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'Kolea', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'Sidi Ghiles', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'El Attaf', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'Ain Tagourait', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'Bou Ismail', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'Hadjout', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'Sidi Amar', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'Gouraya', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'Cherchel', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'El Affroun', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'Larhat', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'Bouharoun', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'Damous El Karita', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'Fouka', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'Bouzegara', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'Ain Al Tine', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'El Boustane', wilaya: 'Tipaza', wilayaCode: 39 },
  { name: 'Ain Boudinar', wilaya: 'Tipaza', wilayaCode: 39 },

  // 40 - Mila
  { name: 'Mila', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Ferraguig', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'El Khemis', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Sidi Merouane', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Tadjennat', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Ain Beida', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Bouhatem', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Rouached', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Tiberguent', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Yahia Beni Guebal', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Beni Khelifa', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Ain Tine', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Ouled Khalouf', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Thaalet El Oued', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'El Mehadjiba', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Souk El Thenine', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Ain Safra', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Minar Zouaouia', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Tebessa', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Ain Melouk', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Oued Endja', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Ahmed Rachedi', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Bouaiouef', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Tachguit', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Amira Ares', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Beni ourtilane', wilaya: 'Mila', wilayaCode: 40 },
  { name: 'Sidi Khelifa', wilaya: 'Mila', wilayaCode: 40 },

  // 41 - Aïn Defla
  { name: 'Ain Defla', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Miliana', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Boumedfaa', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Ain Torki', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Ain Benian', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Zeralda', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'El Attaf', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'El Abadia', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Hammam Righa', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Djelida', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Ain Soltane', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Rouina', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'El Maine', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Tacheta Zougagha', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Oued Chorfa', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Ain Bouyahia', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'El Ghraoua', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Tianet', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Ben Allal', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Oued Djemaa', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Ain Lechiakh', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Oued Kort', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Ain El Turck', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Moussadek', wilaya: 'Ain Defla', wilayaCode: 41 },
  { name: 'Bouhinouna', wilaya: 'Ain Defla', wilayaCode: 41 },

  // 42 - Naâma
  { name: 'Naama', wilaya: 'Naama', wilayaCode: 42 },
  { name: 'Moghrar', wilaya: 'Naama', wilayaCode: 42 },
  { name: 'Ain Sefra', wilaya: 'Naama', wilayaCode: 42 },
  { name: 'Djenane El Beida', wilaya: 'Naama', wilayaCode: 42 },
  { name: 'Makman Ben Amer', wilaya: 'Naama', wilayaCode: 42 },
  { name: 'Ain Yagout', wilaya: 'Naama', wilayaCode: 42 },
  { name: 'Faidh El Emir', wilaya: 'Naama', wilayaCode: 42 },
  { name: 'Mechmia', wilaya: 'Naama', wilayaCode: 42 },
  { name: 'Ain Ben Khelil', wilaya: 'Naama', wilayaCode: 42 },
  { name: 'Sfissifa', wilaya: 'Naama', wilayaCode: 42 },
  { name: 'Mennekhret El Beida', wilaya: 'Naama', wilayaCode: 42 },
  { name: 'Silet', wilaya: 'Naama', wilayaCode: 42 },

  // 43 - Aïn Témouchent
  { name: 'Ain Temouchent', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'El Malah', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'Sidi Ben Adda', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'Ain Kihal', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'El Amria', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'Beni Saf', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'El Auribes', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'El Hamadna', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'Ain El Arbaa', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'Tamzoura', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'Ain Tolba', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'Chaabat El Ham', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'El Gahiz', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'El Malah', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'Beni Oulbane', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'El Messaid', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'Sidi Boumediene', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'El Koudia', wilaya: 'Ain Temouchent', wilayaCode: 43 },
  { name: 'Beni Choukri', wilaya: 'Ain Temouchent', wilayaCode: 43 },

  // 44 - Ghardaïa
  { name: 'Ghardaia', wilaya: 'Ghardaia', wilayaCode: 44 },
  { name: 'Mansoura', wilaya: 'Ghardaia', wilayaCode: 44 },
  { name: 'Djanet', wilaya: 'Ghardaia', wilayaCode: 44 },
  { name: 'El Guerara', wilaya: 'Ghardaia', wilayaCode: 44 },
  { name: 'Berriane', wilaya: 'Ghardaia', wilayaCode: 44 },
  { name: 'El Mehidia', wilaya: 'Ghardaia', wilayaCode: 44 },
  { name: 'El Houta', wilaya: 'Ghardaia', wilayaCode: 44 },
  { name: 'Hassi Fehal', wilaya: 'Ghardaia', wilayaCode: 44 },
  { name: 'Hassi Gara', wilaya: 'Ghardaia', wilayaCode: 44 },
  { name: 'Mekhadma', wilaya: 'Ghardaia', wilayaCode: 44 },
  { name: 'Metlili', wilaya: 'Ghardaia', wilayaCode: 44 },
  { name: 'Sebseb', wilaya: 'Ghardaia', wilayaCode: 44 },
  { name: 'Zelfana', wilaya: 'Ghardaia', wilayaCode: 44 },

  // 45 - Relizane
  { name: 'Relizane', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Oued Rhiou', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Belaassem', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'El Guetna', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Mendes', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Lahlef', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Sidi M\'Hamed Benaouda', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Sidi Khettab', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Oued El Djemaa', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Bendaoud', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'El Matmar', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Ain Taref', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Djidioua', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Ain Rahma', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'El Ouldja', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Had Echkalla', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Hamri', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Oued Essalem', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Ouarizane', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Sidi M\'Hamed', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Yellel', wilaya: 'Relizane', wilayaCode: 45 },
  { name: 'Zidi Moussa', wilaya: 'Relizane', wilayaCode: 45 },

  // 46 - El M'Ghair
  { name: "El M'Ghair", wilaya: "El M'Ghair", wilayaCode: 46 },
  { name: 'Djamaa', wilaya: "El M'Ghair", wilayaCode: 46 },
  { name: 'Mih Ouensa', wilaya: "El M'Ghair", wilayaCode: 46 },
  { name: 'Sidi Aoun', wilaya: "El M'Ghair", wilayaCode: 46 },
  { name: 'Taleb Larbi', wilaya: "El M'Ghair", wilayaCode: 46 },
  { name: 'El Ogla', wilaya: "El M'Ghair", wilayaCode: 46 },
  { name: 'Ourmes', wilaya: "El M'Ghair", wilayaCode: 46 },
  { name: 'Tendla', wilaya: "El M'Ghair", wilayaCode: 46 },
  { name: 'Douar El Ma', wilaya: "El M'Ghair", wilayaCode: 46 },
  { name: 'Magrane', wilaya: "El M'Ghair", wilayaCode: 46 },

  // 47 - El Meniaa
  { name: 'El Meniaa', wilaya: 'El Meniaa', wilayaCode: 47 },
  { name: 'Hassi Gara', wilaya: 'El Meniaa', wilayaCode: 47 },
  { name: 'Hassi Fehal', wilaya: 'El Meniaa', wilayaCode: 47 },
  { name: 'Mekhadma', wilaya: 'El Meniaa', wilayaCode: 47 },

  // 48 - Ouled Djellal
  { name: 'Ouled Djellal', wilaya: 'Ouled Djellal', wilayaCode: 48 },
  { name: 'Bordj El Haouas', wilaya: 'Ouled Djellal', wilayaCode: 48 },
  { name: 'Sidi Khaled', wilaya: 'Ouled Djellal', wilayaCode: 48 },
  { name: 'Charef', wilaya: 'Ouled Djellal', wilayaCode: 48 },
  { name: 'Bougtoub', wilaya: 'Ouled Djellal', wilayaCode: 48 },

  // 49 - Bordj Badji Mokhtar
  { name: 'Bordj Badji Mokhtar', wilaya: 'Bordj Badji Mokhtar', wilayaCode: 49 },
  { name: 'Timiaouine', wilaya: 'Bordj Badji Mokhtar', wilayaCode: 49 },
  { name: 'Tin Zaouin', wilaya: 'Bordj Badji Mokhtar', wilayaCode: 49 },
  { name: 'In Guezzam', wilaya: 'Bordj Badji Mokhtar', wilayaCode: 49 },

  // 50 - Beni Abbes
  { name: 'Beni Abbes', wilaya: 'Beni Abbes', wilayaCode: 50 },
  { name: 'Tamtert', wilaya: 'Beni Abbes', wilayaCode: 50 },
  { name: 'Igli', wilaya: 'Beni Abbes', wilayaCode: 50 },
  { name: 'Kerzaz', wilaya: 'Beni Abbes', wilayaCode: 50 },
  { name: 'Ouled Khodeir', wilaya: 'Beni Abbes', wilayaCode: 50 },
  { name: 'Beni Ikhlef', wilaya: 'Beni Abbes', wilayaCode: 50 },
  { name: 'Timoudi', wilaya: 'Beni Abbes', wilayaCode: 50 },
  { name: 'El Ouata', wilaya: 'Beni Abbes', wilayaCode: 50 },
  { name: 'Abadla', wilaya: 'Beni Abbes', wilayaCode: 50 },
  { name: 'Boukais', wilaya: 'Beni Abbes', wilayaCode: 50 },
  { name: 'Ghalaba', wilaya: 'Beni Abbes', wilayaCode: 50 },

  // 51 - Timimoun
  { name: 'Timimoun', wilaya: 'Timimoun', wilayaCode: 51 },
  { name: 'Ouled Said', wilaya: 'Timimoun', wilayaCode: 51 },
  { name: 'Aougrout', wilaya: 'Timimoun', wilayaCode: 51 },
  { name: 'Deldoul', wilaya: 'Timimoun', wilayaCode: 51 },
  { name: 'Talmine', wilaya: 'Timimoun', wilayaCode: 51 },
  { name: 'Ain El Hadjel', wilaya: 'Timimoun', wilayaCode: 51 },
  { name: 'Tamekten', wilaya: 'Timimoun', wilayaCode: 51 },
  { name: 'Ain Safra', wilaya: 'Timimoun', wilayaCode: 51 },
  { name: 'Zaouiet Kounta', wilaya: 'Timimoun', wilayaCode: 51 },
  { name: 'Timiaouine', wilaya: 'Timimoun', wilayaCode: 51 },

  // 52 - Touggourt
  { name: 'Touggourt', wilaya: 'Touggourt', wilayaCode: 52 },
  { name: 'El Borma', wilaya: 'Touggourt', wilayaCode: 52 },
  { name: 'El Aouinet', wilaya: 'Touggourt', wilayaCode: 52 },
  { name: 'Nezla', wilaya: 'Touggourt', wilayaCode: 52 },
  { name: 'Zaouiet El Aures', wilaya: 'Touggourt', wilayaCode: 52 },
  { name: 'Beni Thabet', wilaya: 'Touggourt', wilayaCode: 52 },
  { name: 'El Hay', wilaya: 'Touggourt', wilayaCode: 52 },
  { name: 'Sidi Slimane', wilaya: 'Touggourt', wilayaCode: 52 },
  { name: 'Taourga', wilaya: 'Touggourt', wilayaCode: 52 },
  { name: 'Megarine', wilaya: 'Touggourt', wilayaCode: 52 },
  { name: 'El Hamra', wilaya: 'Touggourt', wilayaCode: 52 },

  // 53 - Djanet
  { name: 'Djanet', wilaya: 'Djanet', wilayaCode: 53 },
  { name: 'Bordj El Haouas', wilaya: 'Djanet', wilayaCode: 53 },
  { name: 'El Berkevi', wilaya: 'Djanet', wilayaCode: 53 },
  { name: 'Ighzer', wilaya: 'Djanet', wilayaCode: 53 },
  { name: 'Oum El Ichrak', wilaya: 'Djanet', wilayaCode: 53 },

  // 54 - In Salah
  { name: 'In Salah', wilaya: 'In Salah', wilayaCode: 54 },
  { name: 'Tamanrasset', wilaya: 'In Salah', wilayaCode: 54 },
  { name: 'Foggaret Ezzaouia', wilaya: 'In Salah', wilayaCode: 54 },
  { name: 'In Ghar', wilaya: 'In Salah', wilayaCode: 54 },
  { name: 'Aflou', wilaya: 'In Salah', wilayaCode: 54 },

  // 55 - In Guezzam
  { name: 'In Guezzam', wilaya: 'In Guezzam', wilayaCode: 55 },
  { name: 'Tin Zaouin', wilaya: 'In Guezzam', wilayaCode: 55 },
  { name: 'Ain Sefra', wilaya: 'In Guezzam', wilayaCode: 55 },

  // 56 - Touggourt
  { name: 'Touggourt', wilaya: 'Touggourt', wilayaCode: 56 },
  { name: 'El Borma', wilaya: 'Touggourt', wilayaCode: 56 },

  // 57 - Djanet
  { name: 'Djanet', wilaya: 'Djanet', wilayaCode: 57 },
  { name: 'Bordj El Haouas', wilaya: 'Djanet', wilayaCode: 57 },

  // 58 - In Salah
  { name: 'In Salah', wilaya: 'In Salah', wilayaCode: 58 },
  { name: 'Foggaret Ezzaouia', wilaya: 'In Salah', wilayaCode: 58 },
];

async function main() {
  console.log('Seeding communes...');

  // Clear existing communes
  await prisma.commune.deleteMany();

  // Insert all communes
  const result = await prisma.commune.createMany({
    data: communes,
    skipDuplicates: true,
  });

  console.log(`Seeded ${result.count} communes.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
