# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent/v1/agent.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'agent/v1/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61gent/v1/agent.proto\x12\x16\x65\x63omassistant.agent.v1\"\x0f\n\rHealthRequest\"\x9d\x01\n\x0eHealthResponse\x12=\n\x06status\x18\x01 \x01(\x0e\x32-.ecomassistant.agent.v1.HealthResponse.Status\"L\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n\x0eSTATUS_SERVING\x10\x01\x12\x16\n\x12STATUS_NOT_SERVING\x10\x02\"n\n\x15ProcessMessageRequest\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\x13\n\x0bmerchant_id\x18\x03 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x04 \x01(\t\"\x8e\x02\n\x16ProcessMessageResponse\x12I\n\x08\x64\x65\x63ision\x18\x01 \x01(\x0e\x32\x37.ecomassistant.agent.v1.ProcessMessageResponse.Decision\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x1c\n\x0f\x65scalate_reason\x18\x03 \x01(\tH\x00\x88\x01\x01\"i\n\x08\x44\x65\x63ision\x12\x18\n\x14\x44\x45\x43ISION_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x44\x45\x43ISION_REPLY\x10\x01\x12\x15\n\x11\x44\x45\x43ISION_ESCALATE\x10\x02\x12\x18\n\x14\x44\x45\x43ISION_UNAVAILABLE\x10\x03\x42\x12\n\x10_escalate_reason2\xd8\x01\n\x0c\x41gentService\x12W\n\x06Health\x12%.ecomassistant.agent.v1.HealthRequest\x1a&.ecomassistant.agent.v1.HealthResponse\x12o\n\x0eProcessMessage\x12-.ecomassistant.agent.v1.ProcessMessageRequest\x1a..ecomassistant.agent.v1.ProcessMessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent.v1.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=48
  _globals['_HEALTHREQUEST']._serialized_end=63
  _globals['_HEALTHRESPONSE']._serialized_start=66
  _globals['_HEALTHRESPONSE']._serialized_end=223
  _globals['_HEALTHRESPONSE_STATUS']._serialized_start=147
  _globals['_HEALTHRESPONSE_STATUS']._serialized_end=223
  _globals['_PROCESSMESSAGEREQUEST']._serialized_start=225
  _globals['_PROCESSMESSAGEREQUEST']._serialized_end=335
  _globals['_PROCESSMESSAGERESPONSE']._serialized_start=338
  _globals['_PROCESSMESSAGERESPONSE']._serialized_end=608
  _globals['_PROCESSMESSAGERESPONSE_DECISION']._serialized_start=483
  _globals['_PROCESSMESSAGERESPONSE_DECISION']._serialized_end=588
  _globals['_AGENTSERVICE']._serialized_start=611
  _globals['_AGENTSERVICE']._serialized_end=827
# @@protoc_insertion_point(module_scope)
