# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tools/v1/tool.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'tools/v1/tool.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13tools/v1/tool.proto\x12\x16\x65\x63omassistant.tools.v1\"\x0f\n\rHealthRequest\"\x9d\x01\n\x0eHealthResponse\x12=\n\x06status\x18\x01 \x01(\x0e\x32-.ecomassistant.tools.v1.HealthResponse.Status\"L\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n\x0eSTATUS_SERVING\x10\x01\x12\x16\n\x12STATUS_NOT_SERVING\x10\x02\"r\n\x12\x45xecuteToolRequest\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x15\n\rentities_json\x18\x02 \x01(\t\x12\x32\n\x08identity\x18\x03 \x01(\x0b\x32 .ecomassistant.tools.v1.Identity\"M\n\x08Identity\x12\x13\n\x0bmerchant_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x03 \x01(\t\"\xf5\x01\n\x13\x45xecuteToolResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x44\n\x07outcome\x18\x02 \x01(\x0e\x32\x33.ecomassistant.tools.v1.ExecuteToolResponse.Outcome\x12\x11\n\tdata_json\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"e\n\x07Outcome\x12\x17\n\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x13\n\x0fOUTCOME_SUCCESS\x10\x01\x12\x15\n\x11OUTCOME_NOT_FOUND\x10\x02\x12\x15\n\x11OUTCOME_AMBIGUOUS\x10\x03\x32\xce\x01\n\x0bToolService\x12W\n\x06Health\x12%.ecomassistant.tools.v1.HealthRequest\x1a&.ecomassistant.tools.v1.HealthResponse\x12\x66\n\x0b\x45xecuteTool\x12*.ecomassistant.tools.v1.ExecuteToolRequest\x1a+.ecomassistant.tools.v1.ExecuteToolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tools.v1.tool_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=47
  _globals['_HEALTHREQUEST']._serialized_end=62
  _globals['_HEALTHRESPONSE']._serialized_start=65
  _globals['_HEALTHRESPONSE']._serialized_end=222
  _globals['_HEALTHRESPONSE_STATUS']._serialized_start=146
  _globals['_HEALTHRESPONSE_STATUS']._serialized_end=222
  _globals['_EXECUTETOOLREQUEST']._serialized_start=224
  _globals['_EXECUTETOOLREQUEST']._serialized_end=338
  _globals['_IDENTITY']._serialized_start=340
  _globals['_IDENTITY']._serialized_end=417
  _globals['_EXECUTETOOLRESPONSE']._serialized_start=420
  _globals['_EXECUTETOOLRESPONSE']._serialized_end=665
  _globals['_EXECUTETOOLRESPONSE_OUTCOME']._serialized_start=564
  _globals['_EXECUTETOOLRESPONSE_OUTCOME']._serialized_end=665
  _globals['_TOOLSERVICE']._serialized_start=668
  _globals['_TOOLSERVICE']._serialized_end=874
# @@protoc_insertion_point(module_scope)
